version: "3"

volumes:
  static:
  media:
  pg_data:

services:

  postgres:
    image: postgres:13
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    restart: always
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    build: ./frontend/
    env_file: .env
    restart: always
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static/
      - media:/media

  

