#cloud-config
ssh_pwauth: no

users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${SSH_KEY}

write_files:
  - content: |
      #!/bin/bash
      apt-get update
      apt-get install -y docker.io docker-compose
      usermod -aG docker user
    path: /root/docker-install.sh
    permissions: "0740"

runcmd:
  - sleep 120
  - sudo -i
  - /root/docker-install.sh